name = "CrossInverts"
uuid = "2efadbd5-da09-4a26-a84a-7f8cb3b3c09d"
authors = ["Thomas Wutzler <twutz@bgc-jena.mpg.de> and contributors"]
version = "1.0.0-DEV"

[deps]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DistributionFits = "45214091-1ed4-4409-9bcf-fdb48a05e921"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MTKHelpers = "2725b469-bb7f-4d1a-ba58-ced332a70bc7"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
Chain = "0.5.0, 0.6"
ComponentArrays = "0.13.10, 0.14, 0.15"
DataFrames = "1.6.1"
DistributionFits = "0.3.7"
Distributions = "0.25.106"
LoggingExtras = "1.0.3"
MCMCChains = "5.7.1, 6"
MTKHelpers = "0.5.1"
ModelingToolkit = "8.70.0"
OrdinaryDiffEq = "6.58.2"
PDMats = "0.11"
Random = "1.6"
StableRNGs = "1.0.1"
StaticArrays = "1.9"
Tables = "1.11.1"
Test = "1.6"
Turing = "0.21.10, 0.30, 0.33"
julia = "1.6"
